[images]
remote_images = [
  "^(?:https:\\/\\/firebasestorage\\.googleapis\\.com\\/v0\\/b\\/internal-project-22ae3\\.appspot\\.com\\/o(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:http(?:s)?:\\/\\/firebasestorage\\.googleapis\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
]

[context]

  [context.production]

    [context.production.images]
    remote_images = [
      "^(?:https:\\/\\/firebasestorage\\.googleapis\\.com\\/v0\\/b\\/internal-project-22ae3\\.appspot\\.com\\/o(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/firebasestorage\\.googleapis\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

  [context.main]

    [context.main.images]
    remote_images = [
      "^(?:https:\\/\\/firebasestorage\\.googleapis\\.com\\/v0\\/b\\/internal-project-22ae3\\.appspot\\.com\\/o(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/firebasestorage\\.googleapis\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]