import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./footer";
import Header from "./header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Atlas Digital",
  description: "Generated by create next app",
  icons: {
    icon: [
      // For browsers that don't support .svg favicons (Safari):
      {
        rel: 'icon',
        url: '/favicon/logo.png',
        type: 'image/png'
      },

      // For browsers that DO support SVG favicons (most of them now):
      {
        rel: 'icon',
        url: '/favicon/dark.svg',
        type: 'image/svg+xml',
        media: '(prefers-color-scheme: dark)',
      },
      {
        rel: 'icon',
        url: '/favicon/light.svg',
        type: 'image/svg+xml',
        media: '(prefers-color-scheme: light)',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const transparent = false;

  return (
    <html lang="en" style={{ backgroundColor: "#121212" }}>
      <meta name="theme-color" content="#121212"></meta>
      <body className={inter.className}>
        <div className='bg-ad-dark flex flex-col items-center'>
          <div className="sticky top-0 z-50 w-full max-w-[2000px]">
            <Header />
          </div>
          <main
            className="relative flex-grow w-full max-w-[2000px]"
            style={{
              minHeight: "-webkit-fill-available",
              WebkitOverflowScrolling: "touch",
            }}
          >
            {children}
          </main>
          <div className="border-t border-ad-blue w-full max-w-[2000px]">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
